"""
setup_live.py — one-shot local live-test bootstrap.

Reads the existing Streamlit secrets (.streamlit/secrets.toml) and clients.json,
then:
  1. writes backend/.env (AI keys + a generated Fernet key + SQLite + dev bypass),
  2. creates the SQLite dev database + tables,
  3. seeds a dev admin user, your Gmail credential (encrypted), and your clients
     (property IDs encrypted at rest).

Secrets are never printed. Re-runnable: it reuses an existing encryption key if
backend/.env already has one, and replaces seeded credentials/clients cleanly.

Run from the repo root:
    python backend/setup_live.py
"""
from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent
REPO_ROOT = BACKEND_DIR.parent
SECRETS = REPO_ROOT / ".streamlit" / "secrets.toml"
CLIENTS = REPO_ROOT / "clients.json"
ENV_PATH = BACKEND_DIR / ".env"
DB_PATH = BACKEND_DIR / "growth_analyst_dev.db"

# Account that should always have admin access + own the seeded clients.
OWNER_EMAIL = "omkar.rakshe@schbang.com"


def _load_secrets() -> dict:
    if not SECRETS.exists():
        sys.exit(f"ERROR: {SECRETS} not found. Cannot read live credentials.")
    with open(SECRETS, "rb") as f:
        return tomllib.load(f)


def _existing_fernet_key() -> str | None:
    if not ENV_PATH.exists():
        return None
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        if line.startswith("CREDENTIAL_ENCRYPTION_KEY="):
            val = line.split("=", 1)[1].strip()
            return val or None
    return None


def _write_env(secrets: dict, fernet_key: str) -> None:
    import secrets as pysecrets

    g = lambda *path, default="": _dig(secrets, path, default)  # noqa: E731
    db_url = "sqlite:///" + str(DB_PATH).replace("\\", "/")
    lines = [
        "# Auto-generated by setup_live.py for LOCAL live testing. Do not commit.",
        "ENVIRONMENT=development",
        "DEV_AUTH_BYPASS=true",
        f"DEV_USER_EMAIL={OWNER_EMAIL}",
        f"ADMIN_EMAILS={OWNER_EMAIL}",
        "FRONTEND_ORIGIN=http://localhost:5173",
        f"SESSION_SECRET={pysecrets.token_urlsafe(32)}",
        f"CREDENTIAL_ENCRYPTION_KEY={fernet_key}",
        f"DATABASE_URL={db_url}",
        f"AUTH_ALLOWED_DOMAIN={g('auth', 'allowed_domain', default='schbang.com')}",
        f"GEMINI_API_KEY={g('gemini', 'api_key')}",
        f"XAI_API_KEY={g('xai', 'api_key')}",
        f"GOOGLE_PAGESPEED_API_KEY={g('google_pagespeed', 'api_key')}",
        f"CLARITY_API_TOKEN={g('clarity', 'api_token')}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    # Also load into this process so the seeding step below can encrypt/connect.
    for line in lines:
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ[k] = v


def _dig(d: dict, path: tuple, default=""):
    node = d
    for p in path:
        if not isinstance(node, dict) or p not in node:
            return default
        node = node[p]
    return node


def main() -> None:
    secrets = _load_secrets()

    # 1) Encryption key (stable across runs) + .env
    from cryptography.fernet import Fernet

    key = _existing_fernet_key() or Fernet.generate_key().decode()
    _write_env(secrets, key)
    print(f"[ok] wrote {ENV_PATH.relative_to(REPO_ROOT)} (secrets not shown)")

    # 2) Import app AFTER env is set
    sys.path.insert(0, str(BACKEND_DIR))
    from app.db import Base, SessionLocal, engine
    from app.models import Client, Credential, CredentialKind, Role, User
    from app.security.crypto import encrypt_json, encrypt_str

    Base.metadata.create_all(bind=engine)
    print("[ok] created SQLite tables")

    db = SessionLocal()
    try:
        # 3) admin owner user (always-access account)
        email = OWNER_EMAIL.lower()
        user = db.query(User).filter(User.email == email).one_or_none()
        if user is None:
            user = User(email=email, name="Omkar Rakshe", role=Role.admin, is_active=True)
            db.add(user)
            db.commit()
            db.refresh(user)
        else:
            user.role = Role.admin
            user.is_active = True
            db.commit()

        # Clean previous seeded rows for a tidy re-run
        db.query(Client).filter(Client.owner_user_id == user.id).delete()
        db.query(Credential).filter(Credential.owner_user_id == user.id).delete()
        db.commit()

        # 4) credential — prefer user_oauth (matches current working Streamlit path)
        uo = secrets.get("user_oauth", {})
        sa = secrets.get("gcp_service_account", {})
        if uo.get("refresh_token") and uo.get("client_id") and uo.get("client_secret"):
            cred = Credential(
                label="analytics.schbang gmail (user OAuth)",
                kind=CredentialKind.user_oauth,
                blob_enc=encrypt_json({
                    "client_id": uo["client_id"],
                    "client_secret": uo["client_secret"],
                    "refresh_token": uo["refresh_token"],
                }),
                owner_user_id=user.id,
            )
            cred_desc = "user OAuth"
        elif sa.get("private_key"):
            cred = Credential(
                label="GCP service account",
                kind=CredentialKind.service_account,
                blob_enc=encrypt_json(dict(sa)),
                owner_user_id=user.id,
            )
            cred_desc = "service account"
        else:
            sys.exit("ERROR: no usable [user_oauth] or [gcp_service_account] in secrets.toml")
        db.add(cred)
        db.commit()
        db.refresh(cred)
        print(f"[ok] seeded credential ({cred_desc}, encrypted)")

        # 5) clients from clients.json
        import json

        registry = json.loads(CLIENTS.read_text(encoding="utf-8")).get("clients", {})
        n = 0
        for name, cfg in registry.items():
            is_demo = bool(cfg.get("use_demo_data"))
            client = Client(
                display_name=name,
                ga4_property_id_enc=encrypt_str(cfg.get("ga4_property_id", "")) if cfg.get("ga4_property_id") else "",
                gsc_site_url=cfg.get("gsc_site_url", ""),
                organic_only=cfg.get("organic_only", True),
                use_demo_data=is_demo,
                credential_id=None if is_demo else cred.id,
                owner_user_id=user.id,
            )
            db.add(client)
            n += 1
        db.commit()
        print(f"[ok] seeded {n} clients (property IDs encrypted)")
        print("\nDone. Start the backend:  cd backend && uvicorn app.main:app --reload --port 8000")
    finally:
        db.close()


if __name__ == "__main__":
    main()
